// <auto-generated />
using System;
using System.Collections.Generic;
using Bordle.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722015803_AddDailyStreakToGuilds")]
    partial class AddDailyStreakToGuilds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bordle.Server.Data.Models.Guess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("AttemptNumber")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("PuzzleId")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("PuzzleId");

                    b.HasIndex("UserId");

                    b.ToTable("Guesses", t =>
                        {
                            t.HasCheckConstraint("CK_AttemptNumber", "\"AttemptNumber\" BETWEEN 1 AND 6");

                            t.HasCheckConstraint("CK_Guess_Length", "char_length(\"Word\") = 5");
                        });
                });

            modelBuilder.Entity("Bordle.Server.Data.Models.Guild", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("DailyStreak")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Bordle.Server.Data.Models.Puzzle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FallbackWord")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("GeneratedHints")
                        .HasColumnType("varchar(25)[]");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("SubmissionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("Puzzles", t =>
                        {
                            t.HasCheckConstraint("CK_FallbackWord_Length", "\"FallbackWord\" IS NULL OR char_length(\"FallbackWord\") = 5");
                        });
                });

            modelBuilder.Entity("Bordle.Server.Data.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Bordle.Server.Data.Models.WordSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<List<string>>("Hints")
                        .IsRequired()
                        .HasColumnType("varchar(25)[]");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.ToTable("WordSubmissions", t =>
                        {
                            t.HasCheckConstraint("CK_Hints_Count", "array_length(\"Hints\", 1) <= 3");

                            t.HasCheckConstraint("CK_Word_Length", "char_length(\"Word\") = 5");
                        });
                });

            modelBuilder.Entity("Bordle.Server.Data.Models.Guess", b =>
                {
                    b.HasOne("Bordle.Server.Data.Models.Guild", "Guild")
                        .WithMany("Guesses")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bordle.Server.Data.Models.Puzzle", "Puzzle")
                        .WithMany("Guesses")
                        .HasForeignKey("PuzzleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bordle.Server.Data.Models.User", "User")
                        .WithMany("Guesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("Puzzle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bordle.Server.Data.Models.Puzzle", b =>
                {
                    b.HasOne("Bordle.Server.Data.Models.Guild", "Guild")
                        .WithMany("Puzzles")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bordle.Server.Data.Models.WordSubmission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId");

                    b.Navigation("Guild");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Bordle.Server.Data.Models.WordSubmission", b =>
                {
                    b.HasOne("Bordle.Server.Data.Models.Guild", "Guild")
                        .WithMany("WordSubmissions")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bordle.Server.Data.Models.User", "User")
                        .WithMany("WordSubmissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bordle.Server.Data.Models.Guild", b =>
                {
                    b.Navigation("Guesses");

                    b.Navigation("Puzzles");

                    b.Navigation("WordSubmissions");
                });

            modelBuilder.Entity("Bordle.Server.Data.Models.Puzzle", b =>
                {
                    b.Navigation("Guesses");
                });

            modelBuilder.Entity("Bordle.Server.Data.Models.User", b =>
                {
                    b.Navigation("Guesses");

                    b.Navigation("WordSubmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
